export {default as Home} from './Home.jsx'
export {default as Pages} from './Pages.jsx'
export {default as TemplatePage} from './TemplatePage.jsx'
export {default as SignIn} from './SignIn.jsx'
export {default as SignUp} from './SignUp.jsx'