export {default as Blogs} from './Blogs.jsx'
export {default as CallToAction} from './CallToAction.jsx'
export {default as FAQ} from './FAQ.jsx'
export {default as Hero} from './Hero.jsx'
export {default as NewsletterSubscribe } from './NewsletterSubscribe .jsx'
export {default as Rating} from './Rating.jsx'
export {default as Offer} from './Offer.jsx'
export {default as Template} from './Template.jsx'
export {default as Testimonial} from './Testimonial.jsx'
export {default as TwoColumnLayout} from './TwoColumnLayout.jsx'
export {default as SplitContent} from './SplitContent.jsx'
